# Generated by Django 5.0.3 on 2026-03-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="documentos_requeridos",
            field=models.TextField(blank=True, verbose_name="Documentos a llevar"),
        ),
        migrations.AlterField(
            model_name="cita",
            name="fecha",
            field=models.DateField(verbose_name="Fecha de la cita"),
        ),
        migrations.AlterField(
            model_name="cita",
            name="hora",
            field=models.TimeField(verbose_name="Hora de la cita"),
        ),
        migrations.AlterField(
            model_name="cita",
            name="lugar",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Lugar / IPS / Clínica"
            ),
        ),
        migrations.AlterField(
            model_name="cita",
            name="medico",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nombre del médico"
            ),
        ),
        migrations.AlterField(
            model_name="recordatorio",
            name="canal",
            field=models.CharField(
                choices=[
                    ("push", "Push Notification"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                ],
                default="push",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recordatorio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("72h", "72 horas antes"),
                    ("24h", "24 horas antes"),
                    ("2h", "2 horas antes"),
                    ("post", "Post cita (2h después)"),
                ],
                max_length=5,
            ),
        ),
    ]
