# Generated by Django 5.0.3 on 2026-03-04 02:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notificaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logauditoria",
            options={
                "ordering": ["-creado_at"],
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
            },
        ),
    ]
