# Generated by Django 5.0.3 on 2026-03-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="alergias",
            field=models.TextField(blank=True, verbose_name="Alergias conocidas"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="condiciones",
            field=models.TextField(blank=True, verbose_name="Condiciones médicas"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="grupo_sanguineo",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Grupo sanguíneo"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="medicamentos_actuales",
            field=models.TextField(blank=True, verbose_name="Medicamentos actuales"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="numero_afiliacion",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="N° afiliación EPS"
            ),
        ),
    ]
