# Generated by Django 5.0.3 on 2026-03-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pacientes",
            "0002_alter_paciente_alergias_alter_paciente_condiciones_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="cedula",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Cédula de ciudadanía"
            ),
        ),
    ]
