# Generated by Django 5.0.3 on 2026-03-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicamentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrotoma",
            options={
                "ordering": ["-fecha_programada", "-hora_programada"],
                "verbose_name": "Registro de Toma",
                "verbose_name_plural": "Registros de Toma",
            },
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="dias_semana",
            field=models.JSONField(
                blank=True, default=list, help_text="[0,1,2] donde 0=Lunes"
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="dosis",
            field=models.CharField(
                help_text="Ej: 1 tableta, 5ml",
                max_length=100,
                verbose_name="Dosis por toma",
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("pausado", "Pausado temporalmente"),
                    ("suspendido", "Suspendido"),
                ],
                default="activo",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="fecha_inicio",
            field=models.DateField(verbose_name="Fecha inicio tratamiento"),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="frecuencia_tipo",
            field=models.CharField(
                choices=[
                    ("cada_horas", "Cada X horas (ej: cada 8h)"),
                    ("veces_dia", "X veces al día en horarios fijos"),
                    ("dias_esp", "Días específicos de la semana"),
                    ("necesidad", "Solo cuando se necesite (SOS)"),
                ],
                default="veces_dia",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="horarios_fijos",
            field=models.JSONField(
                blank=True, default=list, help_text='["08:00","14:00","20:00"]'
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="instrucciones",
            field=models.TextField(
                blank=True, help_text="Tomar con comida, evitar sol..."
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="intervalo_horas",
            field=models.PositiveIntegerField(
                blank=True, help_text="Ej: 8 para cada 8 horas", null=True
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="nombre",
            field=models.CharField(
                max_length=200, verbose_name="Nombre del medicamento"
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="presentacion",
            field=models.CharField(
                blank=True, help_text="Ej: Tableta 500mg", max_length=100
            ),
        ),
    ]
